# Generated by Django 4.1.5 on 2023-04-29 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('category_description', models.TextField(null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('product_title', models.CharField(max_length=255)),
                ('product_description', models.TextField(null=True)),
                ('product_image', models.ImageField(upload_to='uploads/')),
                ('product_price', models.FloatField(max_length=10)),
                ('discounted_value', models.IntegerField(null=True)),
                ('discounted_type', models.CharField(choices=[('pct', 'Percentage'), ('amt', 'Amount')], max_length=10)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
